
#ifndef _LANG_H
#define _LANG_H

#define W_CGI_ERR "CGI²ÎÊı´íÎó!"
#define W_FLNA_ERR1 "ÎÄ¼ş¼ĞÃû²»ÄÜÎª¿Õ!"
#define W_FLNA_ERR2 "ÎÄ¼ş¼ĞÃû±ØĞëÊÇ×Ö·ûºÍÊı×Ö,²»ÄÜº¬ÓĞ¿Õ¸ñ!"
#define W_FLNA_ERR3 "ÒÑÓĞÍ¬ÃûµÄÎÄ¼ş¼Ğ!"
#define W_FLNA_ERR4 "·Ç·¨µÄÎÄ¼ş¼ĞÃû!"
#define W_SYS_ERR "ÏµÍ³´íÎó!"
#define W_DB_ERR "Êı¾İ¿â³ö´í!"
#define W_PASS_ERR "ÓÃ»§µÇÂ¼¿ÚÁîÊäÈë´íÎó!"
#define W_NO_USER "ÎŞ´ËÓÃ»§µÄ×¢²áĞÅÏ¢!"
#define W_USER_BUSY "ÓÃ»§³åÍ»,ÇëÉÔºóÔÙÊÔ!"
#define W_USER_FOOL "´ËÓÃ»§Ç©ÃûÒÑÊ§Ğ§!"
#define W_NO_MEM "ÄÚ´æ²»×ã!"
#define W_ANS_ERR "ÃÜÂëÌáÊ¾ÎÊÌâ»Ø´ğ´íÎó!"
#define W_NO_PASS "¿ÚÁî²»ÄÜÎª¿Õ,ÇëÖØĞÂ×¢²á!"
#define W_PASS_ERR2 "¿ÚÁîÈ·ÈÏÓĞ´íÎó,ÇëÖØĞÂ×¢²á!"
#define W_NO_QUES "ÃÜÂëÌáÊ¾ÎÊÌâ²»ÄÜÎª¿Õ,ÇëÖØĞÂ×¢²á!"
#define W_NO_QUES2 "ÃÜÂëÌáÊ¾ÎÊÌâ²»ÄÜÎª¿Õ!"
#define W_NO_ANS "ÃÜÂëÌáÊ¾ÎÊÌâµÄ´ğ°¸²»ÄÜÎª¿Õ,ÇëÖØĞÂ×¢²á!"
#define W_NO_ANS2 "ÃÜÂëÌáÊ¾ÎÊÌâµÄ´ğ°¸²»ÄÜÎª¿Õ!"
#define W_ADDUSER_ERR "Ìí¼ÓĞÂÓÃ»§Ê§°Ü!"
#define W_MSR_ERR "ÓÊ¼ş·şÎñÆ÷³ö´í!"
#define W_NO_NAME "Î´ÊäÈëĞÅÏäµÄÓÃ»§Ãû!"
#define W_PASS_BL "ÃÜÂë²»ÄÜÎª¿Õ!"
#define W_PASS_ERR3 "¿ÚÁîÈ·ÈÏÓĞ´íÎó,ÇëÖØĞÂÊäÈë!"
#define W_NO_FOLDER "Ô´ÎÄ¼ş¼Ğ²»´æÔÚ!"
#define W_NO_FOLDER2 "Ä¿µÄÎÄ¼ş¼Ğ²´æÔÚ!"
#define W_NO_RECV "Î´ÌîĞ´ÊÕ¼şÈËµØÖ·!"
#define W_NAME_ERROR1 "ÓÃ»§Ãû±ØĞëÓÉ×ÖÄ¸ºÍÊı×Ö×é³É²¢ÒÔ×ÖÄ¸¿ªÍ·!"
#define W_NAME_ERROR2 "¶Ô²»Æğ,´ËÓÃ»§ÃûÒÑ±»ÆäËûÈËÊ¹ÓÃ,ÇëÖØĞÂÑ¡ÔñÓÃ»§Ãû!"


#define M_SYSINFO "ÏµÍ³ÌáÊ¾ĞÅÏ¢"
#define M_TITLE "Ãâ·ÑÓÊ¼ş"
#define M_LOGFAIL "µÇÂ¼Ê§°Ü"
#define M_RELOG "ÖØĞÂµÇÂ¼"
#define M_LOGOUT "ÍË³öµÇÂ¼"
#define M_INBOX "ÊÕ¼şÏä"
#define M_SENDMAIL "·¢ÓÊ¼ş"
#define M_OUTBOX "·¢¼şÏä"
#define M_DEL "»ØÊÕÕ¾"
#define M_SET "ÓÃ»§ÉèÖÃ"
#define M_HELP "°ïÖú"
#define M_FOLDER1 "ÎÄ¼ş¼Ğ"
#define M_NULL "¿Õ"
#define M_RECV "ÊÕ¼şÈË"
#define M_SEND "·¢¼şÈË"
#define M_NOSUBJ "ÎŞ±êÌâ"
#define M_ATTACH "¸½¼ş"
#define M_SENDGO "ÓÊ¼şÒÑ³É¹¦·¢ËÍ"
#define M_INFO_OK "ÓÃ»§×¢²áĞÅÏ¢ĞŞ¸ÄÍê³É!"
#define M_REGINFO "ÓÃ»§×¢²áĞÅÏ¢"
#define M_REG "ÓÃ»§×¢²á"
#define M_REGNEW "ÖØĞÂ×¢²áĞÂÓÃ»§"
#define M_REGOK "ĞÂÓÃ»§×¢²á³É¹¦"
#define M_LOGNOW "ÏÖÔÚµÇÂ¼"


#endif

